# site settings
title: Women in Technology France
subtitle: by WIT
email: WomenInTechnologyFrance@gmail.com
description: Bienvenue sur le site de "Women In Technology France"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://womenintechnologyfrance.azurewebsites.net"  # the base hostname & protocol for your site
author: Nadege BAUBANT
street_address: 34 Boulevard de charonne
city: Paris
state: France
zip_code: 75020
country: France
phone: 

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 15

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: https://www.linkedin.com/groups/8575209
pinterest_url:
slack_url:
twitter_url: https://twitter.com/WITWomen

# build settings
markdown: kramdown

sass:
  style: compressed
